import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ShopifyBaseHtml from "@/components/custom/shopify-base-html";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Zustand or other global state management could be used here to manage theme
// or other global settings if needed

// Would use it for global time period control if I had more time
// Can wrap the root layout so all children can access the state via setter/getter functions
// eg
// createTimePeriodStore - initial state is output from time function
// create setter getter functions and a reset function

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Preloading the Shopify contexts here */}
        <ShopifyBaseHtml />
        {children}
      </body>
    </html >
  );
}
